### ISSUE TITLE
Is it OK to use gcc as the compiler?

### ISSUE THREAD

**Issue by NanXiao** [sharklinux/shark#11]
Hi shark,

In prerequisites, you mention "`clang installed in target system`". Does shark project require clang as the compiler? How about gcc?

Thanks!

Best Regards
Nan Xiao

**Comment by sharklinux** [comment]
If you want to use bpf module, you have to depend on clang, because only llvm have bpf backend, gcc don't have it yet.
Install clang is simple, you don't need to install bpf llvm backend, it's already static linked into shark binary.
