### ISSUE TITLE
Could you consider add a DEBUG variable in Makefile?

### ISSUE THREAD

**Issue by NanXiao** [sharklinux/shark#14]
Hi shark,

Could you consider add a `DEBUG` variable in Makefile? Because I think it will make people convenient for debugging or analyzing program:  

```
DEBUG?= -g -ggdb
```

Thanks very much!

Best Regards
Nan Xiao

**Comment by sharklinux** [comment]
I found it enabled debug info in Makefile.

```
%.o : %.c
       $(CC) -MD -g -c $(CFLAGS) $< -o $@
```

If you want let it to be a variable, fell free to send a PR. :)

**Comment by NanXiao** [comment]
Oh, yes, I find it. I think it is OK to open "-g" in development phase. After it is stable, maybe it needs a flag, thanks!
