### ISSUE TITLE
Use newer Luajit edition

### ISSUE THREAD

**Issue by NanXiao** [sharklinux/shark#15]
Hi Shark,

When using `clang` as the compiler, there will be some errors and warnings in building `Luajit`:  

```
......
clang: error: unsupported option '-dumpspecs'
clang: error: no input files
......
clang: warning: argument unused during compilation: '-fPIC'
clang: warning: argument unused during compilation: '-fomit-frame-pointer'
clang: warning: argument unused during compilation: '-D_FILE_OFFSET_BITS=64'
clang: warning: argument unused during compilation: '-D _LARGEFILE_SOURCE'
......
```

After discussing with `Luajit`'s author, he said in `Luajit 2.0.4`, there is no errors, and in `v2.1` branch, the warnings are gone too ([Using clang compiler build Luajit 2.0.3 generate many errors and warnings](http://www.freelists.org/post/luajit/Using-clang-compiler-build-Luajit-203-generate-many-errors-and-warnings,1)).  

So could you consider upgrade `Luajit 2.0.4`? At least there is no error at all.

Best Regards
Nan Xiao

**Comment by sharklinux** [comment]
Upgraded luajit to 2.0.4, please try again.

**Comment by NanXiao** [comment]
Fix it, thanks!
