### ISSUE TITLE
Modification suggestion about main() function in core/shark.c

### ISSUE THREAD

**Issue by NanXiao** [sharklinux/shark#17]
Hi Shark,

I have read the "`main()`" function in "`core/shark.c`", and find there may be some tiny flaws. For example,  the code may return, goto, or exit(). Definitely, these will not affect the function, but I think the code could be better. Do you mind I modify it? If you think it is no need to do this thing, that also be OK!

Thanks!
Best Regards
Nan Xiao

**Comment by sharklinux** [comment]
Hi,

Sorry for the delay reply, I've been travel in these days.
Please feel free to make code better.

Btw, I've been busy on company affairs(related with relocation things) in these days, maybe will end in August, hope I can put more efforts on shark project after those things done.
