### ISSUE TITLE
Building on ubuntu 15.04 exposes dependency on gcc 4.8 paths

### ISSUE THREAD

**Issue by pcn** [sharklinux/shark#2]
In `shark/perf/perf.d` there are paths that specify gcc version 4.8:

```
$ grep 4.8 perf/perf.d
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h \
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdarg.h \
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h /usr/include/stdint.h \
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed/limits.h \
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed/syslimits.h \
 perf/perf.h /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdbool.h \
```

However the version of gcc the distro ships with is 4.9:

```
$ gcc --version
gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I don't see where perf/perf.d is being generated.  Could this process be part of the Makefile so that the appropriate paths can be generated at build-time?

**Comment by pcn** [comment]
Other files that have 4.8 hardwired:

```
bpf/bpf.d
bpf/libbpf/libbpf.d
bpf/libbpf/bpf_load.d
bpf/bpf.lua 
core/luv/luv.d 
core/shark.d
```

**Comment by pcn** [comment]
So what I'd like to do is know what script/process whatever you have to generate the paths for the .d file (and for bpf.lua) and make it dynamic.  Let me know how I can help.

**Comment by sharklinux** [comment]
It's my fault, I shouldn't push those *.d file into repository, it's gcc generated.
Now it fixed, thank you for this report.

**Comment by pcn** [comment]
Great, it's working for me now.

**Comment by rubenvb** [comment]
The issue is still present in current git master, see [stackoverflow.com](http://stackoverflow.com/questions/30751029/why-does-gcc-search-header-files-from-non-exist-folders/30752388#30752388).

**Comment by sharklinux** [comment]
All .d files should be already removed from git repo now.
