### ISSUE TITLE
What os/distro do you use to develop on?

### ISSUE THREAD

**Issue by pcn** [sharklinux/shark#3]
What do you use to get to a running OS that you can build and test shark on?

**Comment by sharklinux** [comment]
ubuntu.

It should be os-independent to build shark, if you found any build issue on other Linux platform, please raise a issue.

**Comment by pcn** [comment]
I'm trying to build it with ubuntu 15.04 with a mainline kernel build (http://kernel.ubuntu.com/~kernel-ppa/mainline/).  That only includes the kernel headers for perf+ebpf, though.  I'm trying to find out where I can get the linux-libc-dev package you're using that includes a perf_event.h that includes the ebpf definitions.

Thanks!

**Comment by sharklinux** [comment]
I think perf_event.h is located in kernel header files instead of libc-dev package.
If you want to build ebpf, make sure based on Linux kernel 4.0+.

**Comment by sharklinux** [comment]
BTW, if you just want to try perf module other than ebpf, then you can "make BPF_DISABLE=1", there don't have any kernel version requirement for build perf module.

Thanks.

**Comment by pcn** [comment]
So I've done this to describe how I just got it to build (there may be more for me to get this working, still. But it builds now!):

https://github.com/pcn/shark/blob/build-on-ubuntu-15-04/README.md#ubuntu
